Repository dynawo/dynawo, pull requests merged in 2020-12, with the labels that each got.

#1302 #902 Correct comments
  dynawo/sources/API/PAR/PARParametersSet.h
Labels: bug

#1313 #902 Update zip library interface
  dynawo/3rdParty/libzip/include/libzip/ZipEntry.h
Labels: bug

#1329 #1328 Correct c++11 compilation with clang
  dynawo/3rdParty/libxml/sax/parser/include/xml/sax/parser/ComposableDocumentHandler.h
  dynawo/3rdParty/libxml/sax/parser/include/xml/sax/parser/ComposableElementHandler.h
  dynawo/3rdParty/libxml/sax/parser/include/xml/sax/parser/DocumentHandler.h
  dynawo/3rdParty/libxml/sax/parser/include/xml/sax/parser/ElementHandler.h
  dynawo/3rdParty/libxml/sax/parser/src/DocumentHandler.cpp
  dynawo/3rdParty/libxml/sax/parser/src/ElementHandler.cpp
Labels: 3rd party, bug

#1330 #1314 Implement multithreading for traces
  dynawo/sources/Common/DYNTrace.cpp
  dynawo/sources/Common/DYNTrace.h
Labels: Bug

#1349 #1348 Add a PMaxPu parameter to the DynaFlow HVDC models
  dynawo/sources/Modeler/DataInterface/IIDM/DYNHvdcLineInterfaceIIDM.cpp
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
  examples/DynaFlow/IllustrativeExamples/HVDC_CLA/HVDC_CLA.par
  examples/DynaFlow/IllustrativeExamples/HVDC_PhaseShifter/HVDC_PhaseShifter.par
  nrt/data/DynaFlow/HvdcDangling/HvdcDangling.par
  util/xsl/1348.par.xsl
Labels: DynaFlow, Models library

#1355 #1314 Correct traces in static compilation
  dynawo/sources/Common/DYNTrace.cpp
  dynawo/sources/Common/DYNTrace.h
Labels: Bug
