Repository dynawo/dynawo, pull requests merged in 2020-11, with the labels that each got.

#1238 #1235 Correct parsing of delays
  dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py
Labels: bug

#1252 #1251 Add an xsl for DynaFlow generators parameters URef0Pu and PRef0Pu
  util/xsl/1246.par.xsl
Labels: DynaFlow

#1254 #1191 Fix name in ACEmulation
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation.mo
Labels: Models library

#1232 #570 Update to sundials 5.3.0 and suitesparse 5.4.0
  .gitignore
  README.md
  dynawo/3rdParty/CMakeLists.txt
  dynawo/3rdParty/sundials/patch/MSVC/sundials.patch
  dynawo/3rdParty/sundials/patch/common/sundials.patch
  dynawo/3rdParty/sundials/patch/nicslu/sundials.patch
  dynawo/cmake/FindSundials.cmake
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINAlgRestoration.cpp
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.cpp
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINEuler.cpp
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINEuler.h
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINSubModel.cpp
  dynawo/sources/Solvers/AlgebraicSolvers/test/TestBasics.cpp
  dynawo/sources/Solvers/SolverIDA/DYNSolverIDA.cpp
Labels: enhancement

#1280 #1279 Add a new _INIT model for the recaculation of the limits of the restorative load
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/LoadAlphaBetaRestorativeLimitsRecalc_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Loads/package.order
  dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt
  dynawo/sources/Models/Modelica/PreassembledModels/LoadAlphaBetaRestorativeLimitsRecalc.xml
Labels: Models library

#1286 #1100 Filter messages before streaming them in internal buffer
  .gitignore
  dynawo/sources/Common/DYNTrace.cpp
  dynawo/sources/Common/DYNTrace.h
  dynawo/sources/Common/DYNTraceStream.cpp
  dynawo/sources/Common/DYNTraceStream.h
Labels: enhancement
