Repository dynawo/dynawo, pull requests merged in 2020-10, with the labels that each got.

#1182 #1181 Provide optional data interface to simulation
  dynawo/sources/Simulation/DYNSimulation.cpp
  dynawo/sources/Simulation/DYNSimulation.h
Labels: DynaFlow, enhancement

#1188 #1181 Correct default argument value in simulation
  dynawo/sources/Simulation/DYNSimulation.h
Labels: bug

#1190 #1189 Correct trace appenders
  dynawo/sources/Common/DYNTrace.cpp
  dynawo/sources/Common/DYNTrace.h
Labels: Code quality

#1214 #1213 Refactor some usage help.
  README.md
  dynawo/3rdParty/CMakeLists.txt
  dynawo/sources/Launcher/dynawo.cmd.in
  dynawo/sources/Launcher/dynawo.sh
  dynawo/sources/Launcher/launcher.in
  dynawo/sources/Launcher/main.cpp
Labels: Ease of Use
