Repository dynawo/dynawo, pull requests merged in 2021-10, with the labels that each got.

#1895 #1894 speed up iidm parsing using lxml
  util/nrt_diff/iidmDiff.py
  util/nrt_diff/nrtDiff.py
Labels: Enhancement

#1904 #1900 Fix regulated terminal
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.cpp
Labels: Bug, DynaFlow

#1905 #1901 Fix types in DynaFlow models
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/BaseClasses.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQProp.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQPropDiagramPQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVProp.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemote.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemoteDiagramPQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/SVarCPV.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/SVarCPVRemote.mo
Labels: Models library, DynaFlow

#1907 #1894 Fix python unit tests
  util/nrt_diff/nrtDiff.py
  util/timeline_filter/test/filtered_timeline_ref.xml
Labels: Bug
