Repository dynawo/dynawo, pull requests merged in 2021-04, with the labels that each got.

#1554 #1553 add missing break statement
  dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.cpp
Labels: Bug, DynaFlow, Models library

#1536 #1532 Upgrade to 1.3.2 version of powsybl-iidm4cpp
  dynawo/3rdParty/libiidm/libiidm.cmake
  dynawo/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNFictTwoWTransformerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNShuntCompensatorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNThreeWTransformerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestDataInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestFictVoltageLevelInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestServiceManagerInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestShuntCompensatorInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestThreeWTransformerInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestVoltageLevelInterface.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestIIDMInitializationFlow.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestShuntCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestThreeWindingsTransformer.cpp
  util/envDynawo.sh
Labels: 3rd party

#1560 #1559 Fix OmegaRef calculation in Grid Forming Converters NRT
  nrt/data/GridFormingConverters/GridFormingConverters.dyd
  nrt/data/GridFormingConverters/GridFormingConverters.par
  nrt/data/GridFormingConverters/reference/outputs/curves/curves.csv
Labels: Enhancement

#1557 #1551 Remove model of generator with impedance
  dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt
  dynawo/sources/Models/Modelica/PreassembledModels/GeneratorPVDiagramPQWithImpedanceSignalN.xml
  dynawo/sources/Models/Modelica/PreassembledModels/GeneratorPVWithImpedanceSignalN.xml
Labels: DynaFlow, Enhancement, Models library

#1562 #1561 adapting shunt data interface and model to use NonLinearShunts
  dynawo/sources/Modeler/DataInterface/DYNShuntCompensatorInterface.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNShuntCompensatorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNShuntCompensatorInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestShuntCompensatorInterface.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.h
  dynawo/sources/Models/CPP/ModelNetwork/test/TestShuntCompensator.cpp
Labels: 3rd party, Enhancement

#1566 #1561 adapting shunt data interface for iidm 1.0
  dynawo/sources/Modeler/DataInterface/IIDM/DYNShuntCompensatorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/IIDM/DYNShuntCompensatorInterfaceIIDM.h
Labels: 3rd party, Enhancement

#1576 #1574 Correct git config ins scripts
  util/envDynawo.sh
Labels: Bug, DevOps

#1584 #1574 Correct autocompletion
  util/envDynawo.sh
Labels: Bug

#1590 #1589 fix shunt doc for older doxygen versions
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNShuntCompensatorInterfaceIIDM.h
Labels: Bug

#1601 #1600 BaseGeneratorSynchronous
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses.mo
Labels: Models library

#1596 #1594 Correct unit tests
  dynawo/sources/Models/CPP/ModelNetwork/test/TestLoad.cpp
Labels: Bug

#1614 #1613 fix shunt centralized model for cpp 98
  dynawo/sources/Models/CPP/Controls/Shunts/ModelCentralizedShuntsSectionControl/DYNModelCentralizedShuntsSectionControl.h
Labels: Bug

#1618 #1617 Get rid of the Modelica shunt regulation for DynaFlow
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Shunts/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Shunts/SectionControl.extvar
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Shunts/SectionControl.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Shunts/SectionControl_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Shunts/package.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Shunts/package.order
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/package.order
  dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt
  dynawo/sources/Models/Modelica/PreassembledModels/ShuntBWithSectionsWithRegulation.xml
  nrt/data/DynaFlow/ShuntWithRegulation/Shunt.crv
  nrt/data/DynaFlow/ShuntWithRegulation/Shunt.dyd
  nrt/data/DynaFlow/ShuntWithRegulation/Shunt.iidm
  nrt/data/DynaFlow/ShuntWithRegulation/Shunt.jobs
  nrt/data/DynaFlow/ShuntWithRegulation/Shunt.par
  nrt/data/DynaFlow/ShuntWithRegulation/ShuntSections.txt
  nrt/data/DynaFlow/ShuntWithRegulation/description/ShuntWithRegulation.eps
  nrt/data/DynaFlow/ShuntWithRegulation/description/Shunts.tex
  nrt/data/DynaFlow/ShuntWithRegulation/reference/outputs/curves/curves.csv
  nrt/data/DynaFlow/ShuntWithRegulation/solvers.par
  nrt/data/DynaFlow/cases.py
Labels: DynaFlow
