Repository dynawo/dynawo, pull requests merged in 2021-06, with the labels that each got.

#1670 #1668 Fix Converter init
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/Converter.mo
Labels: Bug, DynaSwing

#1687 #1668 Fix converter init in v1.2.2
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/Converter.mo
Labels: Bug, DynaSwing

#1724 #1723 Update boost patch for 1.70 on MSVC.
  dynawo/3rdParty/boost/patch/MSVC/boost.patch
Labels: 3rd party

#1732 #1731 Fix dangling line state change
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.cpp
Labels: Bug

#1740 #1728 expose targetDeadBand values for Ratio and Phase Tap Changers
  dynawo/sources/Modeler/DataInterface/DYNPhaseTapChangerInterface.h
  dynawo/sources/Modeler/DataInterface/DYNRatioTapChangerInterface.h
  dynawo/sources/Modeler/DataInterface/IIDM/DYNPhaseTapChangerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/IIDM/DYNPhaseTapChangerInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/IIDM/DYNRatioTapChangerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/IIDM/DYNRatioTapChangerInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/IIDM/test/TestStateVariable.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNPhaseTapChangerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNPhaseTapChangerInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNRatioTapChangerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNRatioTapChangerInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestPhaseTapChangerInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestRatioTapChangerInterface.cpp
Labels: Accuracy, DynaFlow, Enhancement
