Repository dynawo/dynawo, pull requests merged in 2021-11, with the labels that each got.

#1948 #1934 Implement intermediate dump states during simu
  dynawo/sources/API/JOB/JOBFinalStateEntry.h
  dynawo/sources/API/JOB/JOBFinalStateEntryImpl.cpp
  dynawo/sources/API/JOB/JOBFinalStateEntryImpl.h
  dynawo/sources/API/JOB/JOBOutputsEntry.h
  dynawo/sources/API/JOB/JOBOutputsEntryImpl.cpp
  dynawo/sources/API/JOB/JOBOutputsEntryImpl.h
  dynawo/sources/API/JOB/JOBXmlHandler.cpp
  dynawo/sources/API/JOB/test/TestFinalStateEntry.cpp
  dynawo/sources/API/JOB/test/TestOutputsEntry.cpp
  dynawo/sources/API/JOB/test/TestXmlImporter.cpp
  dynawo/sources/API/JOB/test/res/jobsExample.jobs
  dynawo/sources/API/JOB/xsd/jobs.xsd
  dynawo/sources/Common/Dictionaries/DYNError_en_GB.dic
  dynawo/sources/Common/Dictionaries/DYNLog_en_GB.dic
  dynawo/sources/Simulation/DYNSimulation.cpp
  dynawo/sources/Simulation/DYNSimulation.h
  dynawo/sources/Simulation/DYNSimulationLauncher.cpp
  examples/DynaFlow/IllustrativeExamples/HVDC_CLA/HVDC_CLA.jobs
  examples/DynaFlow/IllustrativeExamples/HVDC_PhaseShifter/HVDC_PhaseShifter.jobs
  examples/DynaFlow/IllustrativeExamples/LoadRestoration/LoadRestoration.jobs
  examples/DynaFlow/IllustrativeExamples/PhaseShifters/PhaseShifters.jobs
  examples/DynaWaltz/IEEE14/IEEE14_CascadingLineTrippings/IEEE14.jobs
  examples/DynaWaltz/IEEE14/IEEE14_GeneratorDisconnections/IEEE14.jobs
  examples/DynaWaltz/IEEE57/IEEE57_GeneratorDisconnection/IEEE57.jobs
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectGroup/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLine/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_LoadVariation/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroStaticRefs/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ModelicaModel/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_CurrentLimitAutomaton/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_PhaseShifterI/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_PhaseShifterP/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChangerBlocking/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChangerCpp/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_UnderVoltageAutomaton/IEEE14.jobs
Labels: Enhancement

#1968 #1967 Fix unit tests
  dynawo/sources/API/JOB/test/TestFinalStateEntry.cpp
  dynawo/sources/API/JOB/test/TestXmlImporter.cpp
Labels: Bug

#1978 #1976 adding boolean to determine is CPP model is starting from dump …
  dynawo/sources/Models/CPP/Common/DYNModelCPPImpl.cpp
  dynawo/sources/Models/CPP/Common/DYNModelCPPImpl.h
Labels: Models library, Initialization, DynaWaltz

#1981 #1976 adding boolean to determine is CPP model is starting from dump …
  dynawo/sources/Models/CPP/Common/DYNModelCPP.cpp
  dynawo/sources/Models/CPP/Common/DYNModelCPP.h
Labels: Models library, Initialization, DynaWaltz

#1979 #1977 fix hvdc models when running is false (v1.2.2)
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/InjectorIDQ.mo
Labels: Bug, Models library, DynaWaltz

#1984 #1982 Remove hardcoded path for IIDM_EXT_ xsd path and use env var li…
  dynawo/3rdParty/libiidm/extensions/activePowerControl/xml/src/ActivePowerControlHandler.cpp
  dynawo/3rdParty/libiidm/extensions/congestionManagement/xml/src/CongestionManagementHandler.cpp
  dynawo/3rdParty/libiidm/extensions/generatorOperatorActivePowerRange/xml/src/GeneratorOperatorActivePowerRangeHandler.cpp
  dynawo/3rdParty/libiidm/extensions/stateOfCharge/xml/src/StateOfChargeHandler.cpp
  dynawo/3rdParty/libiidm/extensions/voltageRegulation/xml/src/VoltageRegulationHandler.cpp
Labels: Bug

#1920 #125 fix clang compilation: remove useless flags, keep needed
  dynawo/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/IIDM/DYNBatteryInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.h
Labels: Code quality

#1995 Adding TapChanger blocking models monitoring voltage on up to 5 buses (v1.2.2)
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/TapChangerBlocking3.extvar
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/TapChangerBlocking3.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/TapChangerBlocking4.extvar
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/TapChangerBlocking4.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/TapChangerBlocking5.extvar
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/TapChangerBlocking5.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/package.order
  dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt
  dynawo/sources/Models/Modelica/PreassembledModels/TapChangerBlockingAutomaton3.xml
  dynawo/sources/Models/Modelica/PreassembledModels/TapChangerBlockingAutomaton4.xml
  dynawo/sources/Models/Modelica/PreassembledModels/TapChangerBlockingAutomaton5.xml
Labels: Enhancement, DynaWaltz

#1836 #1834 Add -O0 optim flag to the build of some 3rd parties. Use debug …
  dynawo/3rdParty/CMakeLists.txt
  dynawo/3rdParty/libiidm/libiidm.cmake
  dynawo/CMakeLists.txt
  dynawo/cmake/FindGMock.cmake
Labels: 3rd party

#1993 #1989 Fix Hvdc Dangling for DynaFlow V122
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
Labels: DynaWaltz, DynaFlow

#1992 #1989 Fix Hvdc Dangling for DynaFlow
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDangling.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDanglingDiagramPQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDangling.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDanglingDiagramPQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPVDangling.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPVDanglingDiagramPQ.mo
Labels: DynaWaltz, DynaFlow

#1973 #1971 Use tcmalloc in pre load
  .gitignore
  dynawo/3rdParty/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/IIDM/test/TestIIDMModelsStaticParameters.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestBus.cpp
  util/envDynawo.sh
Labels: Performance

#1864 #1860 Remove impl pattern for network components
  dynawo/sources/Models/CPP/ModelNetwork/CMakeLists.txt
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelGenerator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelGenerator.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelHvdcLink.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelHvdcLink.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLoad.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLoad.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelSwitch.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelSwitch.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelThreeWindingsTransformer.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelThreeWindingsTransformer.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelVoltageLevel.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelVoltageLevel.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.hpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponentImpl.h
  util/warnings_to_filter.txt
Labels: Code quality

#2017 #1934 Update nrt references
  examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/base/finalState/500_outputIIDM.xml
  examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/base/finalState/700_outputIIDM.xml
  examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/base/finalState/outputIIDM.xml
  examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/restart/finalState/700_outputIIDM.xml
  examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/restart/finalState/outputIIDM.xml
Labels: Bug

#2013 #2012 Fix logging for upper projects
  dynawo/sources/Common/DYNTrace.cpp
  dynawo/sources/Common/DYNTrace.h
  dynawo/sources/Common/DYNTraceStream.cpp
  dynawo/sources/Simulation/DYNSimulation.cpp
  util/warnings_to_filter.txt
Labels: Bug
