Repository dynawo/dynawo, pull requests merged in 2021-07, with the labels that each got.

#1764 #1735 Correct centos6 and centos7 compilation
  dynawo/sources/Modeler/DataInterface/IIDM/test/TestDataInterfaceIIDM.cpp
Labels: Bug

#1765 #1735 Correct centos6 and centos7 compilation (switch interface)
  dynawo/sources/Modeler/DataInterface/IIDM/test/TestDataInterfaceIIDM.cpp
Labels: Bug

#1757 #1756 Remove use of deprecated boost timer in c++11
  CPPLINT.cfg
  dynawo/sources/Common/DYNTimer.cpp
  dynawo/sources/Common/DYNTimer.h
Labels: Code quality

#1770 #1749 Correct comments for doxygen on centos6
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensionsTraits.hpp
Labels: Bug

#1780 #1779 Add a Conv2_state variable in the HvdcVSCDangling models
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSCDanglingP.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSCDanglingUdc.mo
Labels: DynaWaltz, Models library

#1785 1775 fix omc build
  dynawo/3rdParty/CMakeLists.txt
Labels: 3rd party, Bug

#1777 #1775 Fix CI for v12x using new docker image dedicated for v12x.
  .github/workflows/ci.yml
Labels: DevOps

#1789 #1735 Correct flag for powsybl use
  dynawo/sources/Modeler/DataInterface/DYNDataInterfaceFactory.cpp
Labels: Bug

#1790 #1735 Correct flag for powsybl use
  dynawo/sources/Modeler/DataInterface/DYNDataInterfaceFactory.cpp
Labels: Bug
