Repository dynawo/dynawo, pull requests merged in 2021-01, with the labels that each got.

#1369 1335 add get regulated bus api
  dynawo/sources/Modeler/DataInterface/DYNServiceManagerInterface.h
  dynawo/sources/Modeler/DataInterface/IIDM/DYNServiceManagerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/IIDM/DYNServiceManagerInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestServiceManagerInterface.cpp
Labels: DynaFlow, Enhancement

#1384 #1380 Fix the use of pu in the models of generators with remote voltage regulation
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.extvar
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemote.extvar
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemote.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemoteDiagramPQ.extvar
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPVRemoteDiagramPQ.mo
Labels: Bug, DynaFlow, Models library

#1334 #1249 Update Adept version
  .vscode/settings.json
  dynawo/3rdParty/CMakeLists.txt
  dynawo/3rdParty/adept/patch/MSVC/adept.patch
  dynawo/3rdParty/adept/patch/common/adept.patch
Labels: Enhancement

#1411 #1404 Put IIDM nrt diff in a specific file
  .vscode/settings.json
  util/nrt_diff/iidmDiff.py
  util/nrt_diff/nrtDiff.py
Labels: DynaFlow, Enhancement
