Repository dynawo/dynawo, pull requests merged in 2021-05, with the labels that each got.

#1630 Update location of unit tests in cmake
  dynawo/sources/API/CRT/CMakeLists.txt
  dynawo/sources/API/CRV/CMakeLists.txt
  dynawo/sources/API/CSTR/CMakeLists.txt
  dynawo/sources/API/DYD/CMakeLists.txt
  dynawo/sources/API/EXTVAR/CMakeLists.txt
  dynawo/sources/API/FS/CMakeLists.txt
  dynawo/sources/API/JOB/CMakeLists.txt
  dynawo/sources/API/PAR/CMakeLists.txt
  dynawo/sources/API/TL/CMakeLists.txt
  dynawo/sources/CMakeLists.txt
  dynawo/sources/Common/CMakeLists.txt
  dynawo/sources/Modeler/Common/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/IIDM/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/CMakeLists.txt
  dynawo/sources/Modeler/ModelManager/CMakeLists.txt
  dynawo/sources/Modeler/util/CMakeLists.txt
  dynawo/sources/ModelicaCompiler/CMakeLists.txt
  dynawo/sources/Models/CMakeLists.txt
  dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/CMakeLists.txt
  dynawo/sources/Models/CPP/Controls/Shunts/ModelCentralizedShuntsSectionControl/CMakeLists.txt
  dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/CMakeLists.txt
  dynawo/sources/Models/CPP/ModelNetwork/CMakeLists.txt
  dynawo/sources/Models/CPP/ModelVariationArea/CMakeLists.txt
  dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt
  dynawo/sources/Solvers/AlgebraicSolvers/CMakeLists.txt
  dynawo/sources/Solvers/Common/CMakeLists.txt
  dynawo/sources/Solvers/SolverIDA/CMakeLists.txt
  dynawo/sources/Solvers/SolverSIM/CMakeLists.txt
  dynawo/sources/Solvers/util/CMakeLists.txt
Labels: DevOps

#1634 #1631 Fix IRotorPu calculation and thetaInternal initialization in the SG model
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/GeneratorSynchronous.mo
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____1_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____2_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____3_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____6_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_BlackBoxModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____8_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-GEN____1_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-GEN____2_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-GEN____3_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-GEN____6_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroConnects/reference/outputs/initValues/globalInit/dumpInitValues-GEN____8_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroStaticRefs/reference/outputs/initValues/globalInit/dumpInitValues-GEN____1_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroStaticRefs/reference/outputs/initValues/globalInit/dumpInitValues-GEN____2_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroStaticRefs/reference/outputs/initValues/globalInit/dumpInitValues-GEN____3_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroStaticRefs/reference/outputs/initValues/globalInit/dumpInitValues-GEN____6_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_MacroStaticRefs/reference/outputs/initValues/globalInit/dumpInitValues-GEN____8_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ModelicaModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____1_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ModelicaModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____2_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ModelicaModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____3_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ModelicaModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____6_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_ModelicaModel/reference/outputs/initValues/globalInit/dumpInitValues-GEN____8_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____1_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____2_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____3_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____6_SM.txt
  nrt/data/IEEE14/IEEE14_SyntaxExamples/IEEE14_TemplateModels/reference/outputs/initValues/globalInit/dumpInitValues-GEN____8_SM.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-GEN___12_SM.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-GEN____1_SM.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-GEN____2_SM.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-GEN____3_SM.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-GEN____6_SM.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-GEN____8_SM.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-GEN____9_SM.txt
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm/reference/outputs/initValues/globalInit/dumpInitValues-SM.txt
Labels: DynaSwing, DynaWaltz, Models library

#1582 #1462 add exception when numerical error causes failing of algebraic …
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINAlgRestoration.cpp
Labels: Enhancement, Solvers

#1666 #1664 Fix pu base for HVDC VSC init
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSC.mo
Labels: Bug, DynaWaltz

#1669 #1664 Correct HVDC VSC pu base for init
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSC.mo
Labels: Bug, DynaWaltz
