Repository dynawo/dynawo, pull requests merged in 2021-09, with the labels that each got.

#1817 #1811 Correct doxygen warnings on ubuntu
  dynawo/sources/API/LEQ/LEQLostEquipment.h
  dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.h
  util/warnings_to_filter.txt
Labels: Bug

#1821 #1820 Add log to notify when IIDM extension library is not found
  dynawo/sources/Common/Dictionaries/DYNLog_en_GB.dic
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensions.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensions.hpp
Labels: Enhancement, DevOps

#1816 #1610 Duplicate init parameters
  documentation/functionalDoc/functionalDoc.tex
  dynawo/sources/Solvers/Common/DYNSolverImpl.cpp
  dynawo/sources/Solvers/Common/DYNSolverImpl.h
  dynawo/sources/Solvers/SolverIDA/DYNSolverIDA.cpp
  dynawo/sources/Solvers/SolverSIM/DYNSolverSIM.cpp
  dynawo/sources/Solvers/SolverSIM/test/TestBasics.cpp
  dynawo/sources/Solvers/util/test/res/dumpSolver.desc.xml
  nrt/data/DynaFlow/ShuntsInit/Shunt.crv
  nrt/data/DynaFlow/ShuntsInit/Shunt.dyd
  nrt/data/DynaFlow/ShuntsInit/Shunt.iidm
  nrt/data/DynaFlow/ShuntsInit/Shunt.jobs
  nrt/data/DynaFlow/ShuntsInit/Shunt.par
  nrt/data/DynaFlow/ShuntsInit/ShuntSections.txt
  nrt/data/DynaFlow/ShuntsInit/reference/outputs/curves/curves.csv
  nrt/data/DynaFlow/ShuntsInit/solvers.par
  nrt/data/DynaFlow/cases.py
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLineInit/IEEE14.crv
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLineInit/IEEE14.dyd
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLineInit/IEEE14.iidm
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLineInit/IEEE14.jobs
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLineInit/IEEE14.par
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLineInit/reference/outputs/curves/curves.csv
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLineInit/reference/outputs/logs/dynawo.log
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLineInit/reference/outputs/timeLine/timeline.log
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLineInit/solvers.par
  nrt/data/IEEE14/cases.py
Labels: Enhancement

#1830 #1475 Update log levels
  dynawo/sources/Common/DYNFileSystemUtils.cpp
  dynawo/sources/Modeler/Common/DYNModeler.cpp
  dynawo/sources/Modeler/DataInterface/DYNComponentInterface.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.cpp
Labels: Enhancement, Models library, Ease of Use

#1837 #1818 Fix cp98 implementation
  dynawo/sources/Modeler/DataInterface/IIDM/DYNVscConverterInterfaceIIDM.cpp
Labels: Bug

#1843 #1825 Remove reference for test for timeout simulation
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLine_timeout/reference/outputs/curves/curves.csv
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLine_timeout/reference/outputs/logs/dynawo.log
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLine_timeout/reference/outputs/lostEquipments/lostEquipments.xml
  nrt/data/IEEE14/IEEE14_BasicTestCases/IEEE14_DisconnectLine_timeout/reference/outputs/timeLine/timeline.log
Labels: Bug

#1842 #125 fix clang compilation -Wextra-semi-stmt
  dynawo/sources/Common/gtest_dynawo.h
  dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h
  dynawo/sources/Models/CPP/ModelNetwork/test/TestTwoWindingsTransformer.cpp
Labels: Code quality

#1839 #1838 Fix windows runtime by compiling adept in shared instead of sta…
  dynawo/3rdParty/CMakeLists.txt
Labels: Bug, 3rd party

#1854 #1851 Improve performance for data check coherence
  dynawo/sources/Modeler/Common/DYNConnectorCalculatedVariable.cpp
  dynawo/sources/Modeler/Common/DYNConnectorCalculatedVariable.h
  dynawo/sources/Modeler/Common/DYNSubModel.cpp
  dynawo/sources/Modeler/Common/DYNSubModel.h
  dynawo/sources/Modeler/Common/test/Test.cpp
  dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp
  dynawo/sources/Modeler/ModelManager/DYNModelManager.h
  dynawo/sources/Modeler/ModelManager/DYNModelModelica.h
  dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/headerPatternDefine.py
  dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/modelWriter.py
  dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.h
  dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Init.h
  dynawo/sources/Models/CPP/Common/DYNModelCPP.h
  dynawo/sources/Models/CPP/Common/DYNModelCPPImpl.h
  dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.h
  dynawo/sources/Models/CPP/Controls/Shunts/ModelCentralizedShuntsSectionControl/DYNModelCentralizedShuntsSectionControl.h
  dynawo/sources/Models/CPP/Events/ModelVariationArea/DYNModelVariationArea.h
  dynawo/sources/Models/CPP/Events/ModelVoltageSetPointChange/DYNModelVoltageSetPointChange.h
  dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.h
Labels: Performance

#1859 #1851 Improve performance for data check coherence
  dynawo/sources/Modeler/Common/DYNConnectorCalculatedVariable.cpp
  dynawo/sources/Modeler/Common/DYNConnectorCalculatedVariable.h
  dynawo/sources/Modeler/Common/DYNSubModel.cpp
  dynawo/sources/Modeler/Common/DYNSubModel.h
  dynawo/sources/Modeler/Common/test/Test.cpp
  dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp
  dynawo/sources/Modeler/ModelManager/DYNModelManager.h
  dynawo/sources/Modeler/ModelManager/DYNModelModelica.h
  dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/headerPatternDefine.py
  dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/modelWriter.py
  dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Dyn.h
  dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference/GeneratorPQ_Init.h
  dynawo/sources/Models/CPP/Common/DYNModelCPP.h
  dynawo/sources/Models/CPP/Common/DYNModelCPPImpl.h
  dynawo/sources/Models/CPP/Events/ModelVariationArea/DYNModelVariationArea.h
  dynawo/sources/Models/CPP/Events/ModelVoltageSetPointChange/DYNModelVoltageSetPointChange.h
  dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.h
Labels: Performance

#1862 #1851 Update model multi loops
  dynawo/sources/Modeler/Common/DYNModelMulti.cpp
Labels: Performance, Code quality

#1853 #1851 Update model multi loops
  dynawo/sources/Modeler/Common/DYNModelMulti.cpp
Labels: Performance

#1852 #125 fix clang compilation -Wfloat-conversion
  dynawo/CMakeLists.txt
  dynawo/sources/Common/DYNCommon.cpp
  dynawo/sources/Common/DYNCommon.h
  dynawo/sources/Modeler/Common/DYNModelMulti.cpp
  dynawo/sources/Modeler/DataInterface/DYNComponentInterface.hpp
  dynawo/sources/Modeler/DataInterface/IIDM/DYNVoltageLevelInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.cpp
Labels: Code quality

#1855 #125 fix clang compilation -Wfloat-equal
  dynawo/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCurrentLimitInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestCurrentLimitInterface.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
Labels: Code quality

#1857 #1856 Fix timeline filter namespace.
  util/timeline_filter/timelineFilter.py
Labels: Bug

#1858 #1856 Fix timeline filter namespace.
  util/timeline_filter/timelineFilter.py
Labels: Bug

#1863 #125 fix clang compilation -Wgnu-zero-variadic-macro-arguments
  dynawo/CMakeLists.txt
  dynawo/sources/Common/DYNMacrosMessage.h
Labels: Code quality

#1848 #125 fix clang compilation -Wdouble-promotion
  dynawo/CMakeLists.txt
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
Labels: Code quality

#1861 #125 fix clang compilation -Wglobal-constructors
  dynawo/CMakeLists.txt
  dynawo/sources/API/CRT/CRTXmlHandler.cpp
  dynawo/sources/API/CRT/test/TestXmlImporter.cpp
  dynawo/sources/API/CRV/CRVXmlHandler.cpp
  dynawo/sources/API/CRV/test/TestXmlImporter.cpp
  dynawo/sources/API/DYD/DYDXmlHandler.cpp
  dynawo/sources/API/DYD/test/Test.cpp
  dynawo/sources/API/EXTVAR/EXTVARXmlHandler.cpp
  dynawo/sources/API/EXTVAR/test/Test.cpp
  dynawo/sources/API/FS/FSXmlHandler.cpp
  dynawo/sources/API/FS/test/TestXmlImporter.cpp
  dynawo/sources/API/JOB/JOBXmlHandler.cpp
  dynawo/sources/API/JOB/test/TestXmlImporter.cpp
  dynawo/sources/API/PAR/PARXmlHandler.cpp
  dynawo/sources/API/PAR/test/TestXmlImporter.cpp
  dynawo/sources/Common/gtest_dynawo.h
  dynawo/sources/Modeler/Common/DYNSubModelFactory.cpp
  dynawo/sources/Modeler/Common/DYNSubModelFactory.h
  dynawo/sources/Modeler/Common/test/CompilerTest.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensions.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNIIDMExtensions.hpp
  dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.cpp
  dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h
  dynawo/sources/Solvers/AlgebraicSolvers/test/TestBasics.cpp
  dynawo/sources/Solvers/Common/DYNSolverFactory.cpp
  dynawo/sources/Solvers/Common/DYNSolverFactory.h
  dynawo/sources/Solvers/SolverIDA/test/TestBasics.cpp
  dynawo/sources/Solvers/SolverSIM/test/TestBasics.cpp
Labels: Code quality

#1866 #125 fix clang compilation -Wmissing-noreturn
  dynawo/CMakeLists.txt
  dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.cpp
Labels: Code quality

#1871 #125 fix clang compilation -Wold-style-cast
  dynawo/CMakeLists.txt
  dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp
  dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h
  dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.cpp
  dynawo/sources/Models/CPP/Events/ModelVariationArea/DYNModelVariationArea.cpp
  dynawo/sources/Models/CPP/Events/ModelVoltageSetPointChange/DYNModelVoltageSetPointChange.cpp
  dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelDanglingLine.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLoad.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelSwitch.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestDerivatives.cpp
Labels: Code quality

#1877 #1794 Fix doxygen comments
  dynawo/sources/Modeler/DataInterface/IIDM/DYNBatteryInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.h
Labels: DevOps

#1875 #125 fix clang compilation -Wreserved-id-macro
  dynawo/CMakeLists.txt
  dynawo/sources/Modeler/ModelManager/DYNModelManagerCommon.h
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINCommon.h
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINSubModel.h
Labels: Code quality

#1869 #125 fix clang compilation -Wmissing-variable-declarations
  dynawo/CMakeLists.txt
  dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.h
Labels: Code quality

#1880 #1794 Fix Battery implementation
  dynawo/sources/Modeler/DataInterface/IIDM/DYNBatteryInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/IIDM/DYNDataInterfaceIIDM.h
Labels: Bug

#1882 #1881 Add a BaseHvdcPDangling in V122
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseClasses.mo
Labels: Models library, DynaWaltz

#1874 #1873 Add possibility to use nrt IIDM comparaison manually
  util/nrt_diff/iidmDiff.py
Labels: Ease of Use

#1884 #125 fix clang compilation -Wshorten-64-to-32
  dynawo/CMakeLists.txt
  dynawo/sources/API/JOB/JOBModelerEntry.cpp
  dynawo/sources/API/TL/TLTimeline.cpp
  dynawo/sources/Common/DYNExecUtils.cpp
  dynawo/sources/Common/DYNFileSystemUtils.cpp
  dynawo/sources/Common/DYNGraph.cpp
  dynawo/sources/Common/DYNSparseMatrix.cpp
  dynawo/sources/Modeler/Common/DYNCommonModeler.cpp
  dynawo/sources/Modeler/Common/DYNCompiler.cpp
  dynawo/sources/Modeler/Common/DYNConnector.cpp
  dynawo/sources/Modeler/Common/DYNConnector.h
  dynawo/sources/Modeler/Common/DYNConnectorCalculatedVariable.cpp
  dynawo/sources/Modeler/Common/DYNDynamicData.cpp
  dynawo/sources/Modeler/Common/DYNModelMulti.cpp
  dynawo/sources/Modeler/Common/DYNSubModel.cpp
  dynawo/sources/Modeler/Common/DYNSubModel.h
  dynawo/sources/Modeler/DataInterface/IIDM/DYNPhaseTapChangerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/IIDM/DYNRatioTapChangerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/IIDM/test/TestStateVariable.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBatteryInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCurrentLimitInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDanglingLineInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNFictTwoWTransformerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNHvdcLineInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNInjectorInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLineInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLoadInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNPhaseTapChangerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNRatioTapChangerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNServiceManagerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNShuntCompensatorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNStaticVarCompensatorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNThreeWTransformerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNTwoWTransformerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp
  dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp
  dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.cpp
  dynawo/sources/Modeler/ModelManager/test/Test.cpp
  dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelCurrentLimits.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestDanglingLine.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestLine.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestLoad.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestShuntCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestStaticVarCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestTwoWindingsTransformer.cpp
  dynawo/sources/Simulation/DYNSimulation.cpp
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINAlgRestoration.cpp
  dynawo/sources/Solvers/AlgebraicSolvers/DYNSolverKINSubModel.cpp
  dynawo/sources/Solvers/Common/DYNSolverCommon.cpp
Labels: Code quality

#1887 #1886 improve Dynamic Time Warping distance eval for nrt
  util/nrt_diff/nrtDiff.py
Labels: Enhancement
