Repository dynawo/dynawo, pull requests merged in 2021-12, with the labels that each got.

#2016 #2007 Remove useless copy constructors
  dynawo/sources/Common/DYNIoDico.h
  dynawo/sources/Modeler/Common/DYNConnector.cpp
  dynawo/sources/Modeler/Common/DYNConnector.h
  dynawo/sources/Modeler/Common/DYNDynamicData.h
Labels: Code quality

#2018 #2006 Remove useless copy constructors
  dynawo/sources/Modeler/DataInterface/DYNStateVariable.cpp
  dynawo/sources/Modeler/DataInterface/DYNStateVariable.h
Labels: Code quality

#2021 #1934 Fix nrt
  examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/base/finalState/500_outputIIDM.xml
  examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/base/finalState/700_outputIIDM.xml
  examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/base/finalState/outputIIDM.xml
  examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/restart/finalState/700_outputIIDM.xml
  examples/DynaFlow/IEEE14/IEEE14_DisconnectLine_intermediate_dump/reference/outputs/restart/finalState/outputIIDM.xml
Labels: Bug

#2027 #1974 Fix solver implementation
  dynawo/sources/Solvers/FixedTimeStep/DYNSolverCommonFixedTimeStep.cpp
  dynawo/sources/Solvers/FixedTimeStep/DYNSolverCommonFixedTimeStep.h
  dynawo/sources/Solvers/FixedTimeStep/SolverSIM/DYNSolverSIM.cpp
  dynawo/sources/Solvers/FixedTimeStep/SolverTRAP/DYNSolverTRAP.cpp
Labels: Bug

#1915 #1910 Implement slack node API
  dynawo/3rdParty/libiidm/libiidm.cmake
  dynawo/3rdParty/libiidm/patch/common/libiidm.patch
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNNetworkInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestNetworkInterface.cpp
Labels: Enhancement, DynaFlow

#2030 #2011 Simplification of power block
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/Power.mo
Labels: Models library, DynaSwing

#2032 #2031 Quoting PATH and LD_LIBRARY_PATH for space handling
  dynawo/CMakeLists.txt
Labels: DevOps

#2028 #1934 Fix cpp98 nrt
  util/nrt_diff/defineTestReference.py
  util/nrt_diff/iidmDiff.py
  util/nrt_diff/nrtDiff.py
  util/nrt_diff/nrtUtils.py
  util/timeline_filter/timelineFilter.py
Labels: Bug

#2046 #2045 New angular p.u. types
  dynawo/sources/Models/Modelica/Dynawo/Types.mo
Labels: Models library
