Repository dynawo/dynawo, pull requests merged in 2022-05, with the labels that each got.

#2297 #2286 Non-zero start value for i0Pu (for branch 460_add_mteret)
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/BaseClasses_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses_INIT.mo
Labels: Bug, DynaSwing

#2309 #2308 Adapt nightly release workflow to publish nightly of release br…
  .github/workflows/nightly-release.yml
Labels: DevOps

#2319 #1528 Fix 5 compilation for windows.
  dynawo/CMakeLists.txt
  dynawo/cmake/FindSundials.cmake
  dynawo/sources/ModelicaCompiler/compileCppModelicaModelInDynamicLib.cmake.in
Labels: 3rd party

#2321 #2051 add assets to release v13
  .github/workflows/release.yml
Labels: DevOps

#2320 #2051 Add more assets to release workflow.
  .github/workflows/release.yml
Labels: DevOps

#2323 #2051 Fix workflow by calling targets to create new distribs.
  .github/workflows/release.yml
Labels: DevOps

#2324 #2051 Fix workflow by calling targets to create new distribs.
  .github/workflows/release.yml
Labels: DevOps

#2337 #2336 Add centos7 distribution generation.
  .github/workflows/release.yml
Labels: DevOps
