Repository dynawo/dynawo, pull requests merged in 2022-06, with the labels that each got.

#2346 #2345 AC Emulation without p0 recalculation
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulationSet_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/package.order
  dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt
  dynawo/sources/Models/Modelica/PreassembledModels/HvdcPQPropDiagramPQEmulationSet.xml
  dynawo/sources/Models/Modelica/PreassembledModels/HvdcPQPropEmulationSet.xml
  dynawo/sources/Models/Modelica/PreassembledModels/HvdcPVDiagramPQEmulationSet.xml
  dynawo/sources/Models/Modelica/PreassembledModels/HvdcPVEmulationSet.xml
Labels: DynaFlow

#2372 #2371 Fix doxygen.
  dynawo/sources/Common/DYNParameter.h
Labels: Documentation

#2367 #2360 Fix windows load of iidm extensions.
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp
Labels: Bug

#2368 2360 iidm extensions windows v13
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDataInterfaceIIDM.cpp
Labels: Bug

#2378 #2376 Update CI workflow to publish doxygen online.
  .github/workflows/ci.yml
Labels: DevOps, Documentation

#2365 2325 add integrator variable limits
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/IntegratorVariableLimits.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/package.order
Labels: Models library, DynaSwing
