Repository dynawo/dynawo, pull requests merged in 2022-09, with the labels that each got.

#2465 #2463 Improve HvdcVSCEmulation init v1.3
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/BaseControls/ACEmulation_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/ActivePowerControl/BaseActivePowerControl.mo
Labels: Models library, DynaWaltz, DynaSwing

#2473 #2366 introducing warm and flat start for model network
  dynawo/sources/Common/Dictionaries/DYNLog_en_GB.dic
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelGenerator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelGenerator.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelHvdcLink.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelHvdcLink.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLoad.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLoad.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNNetworkComponent.h
  dynawo/sources/Models/CPP/ModelNetwork/test/TestBus.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestGenerator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestHvdcLink.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestLoad.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestShuntCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/test/TestStaticVarCompensator.cpp
  util/envDynawo.sh
Labels: Enhancement, Models library, DynaFlow

#2477 #2476 fix isFictitious load interface method
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLoadInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestLoadInterface.cpp
Labels: Bug, DynaFlow

#2479 #2366 fix sonar centos7
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelStaticVarCompensator.cpp
Labels: Code quality

#2503 #2502 Fix No rule to make target M/M/D/N/L/ConstraintKeys.mo
  dynawo/sources/Models/CMakeLists.txt
Labels: Bug
