Repository dynawo/dynawo, pull requests merged in 2022-04, with the labels that each got.

#2252 #2037 Fix nrt following OS 2037
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_3_LoadVarQ/reference/outputs/logs/dynawo.log
Labels: Bug

#2259 #2242 Kludge removed, typing mistake corrected
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/ExcIEEEST4B.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/ExcIEEEST4B_INIT.mo
Labels: Bug, DynaSwing

#2262 #2261 Restore Protected
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/OmegaRef/BaseClasses_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Transformers/BaseClasses_INIT.mo
Labels: DynaSwing

#2260 #1883 Add a TanPhiRef0 for HvdcPTanPhi models
  dynawo/sources/Modeler/DataInterface/IIDM/DYNLccConverterInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLccConverterInterfaceIIDM.cpp
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhi.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDangling.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDanglingDiagramPQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhiDiagramPQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPTanPhi/HvdcPTanPhi_INIT.mo
  nrt/data/DynaFlow/HvdcDangling/HvdcDangling.iidm
  nrt/data/DynaFlow/HvdcDangling/HvdcDangling.par
Labels: Models library, DynaFlow

#2256 #2247 add possibility to connect a calculated discrete variable to a …
  dynawo/sources/Modeler/Common/CMakeLists.txt
  dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.cpp
  dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h
  dynawo/sources/Modeler/Common/DYNModelMulti.cpp
  dynawo/sources/Modeler/Common/DYNModelMulti.h
  dynawo/sources/Modeler/Common/test/Test.cpp
Labels: Enhancement, Initialization
