Repository dynawo/dynawo, pull requests merged in 2022-10, with the labels that each got.

#2474 #2301 switch shunt
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/Switch.extvar
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/Switch.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/package.order
  dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt
  dynawo/sources/Models/Modelica/PreassembledModels/Switch.xml
Labels: DynaFlow

#2523 #2522 Export bus vmax parameter
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBusInterfaceIIDM.cpp
Labels: DynaFlow

#2549 #2548 Allow a size > 5 for array
  dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py
Labels: Enhancement

#2555 #2239 fix windows compil v13
  dynawo/3rdParty/suitesparse/patch/MSVC/suitesparse.patch
Labels: 3rd party
