Repository dynawo/dynawo, pull requests merged in 2022-01, with the labels that each got.

#1906 #1898 Add Q1Ref0Pu, Q2Ref0Pu, U1Ref0Pu, U2Ref0Pu parameters for DynaFlow HVDC models
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQProp.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDangling.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDanglingDiagramPQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPQProp/HvdcPQPropDiagramPQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPV.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPVDangling.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPVDanglingDiagramPQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcPV/HvdcPVDiagramPQ.mo
  examples/DynaFlow/IllustrativeExamples/HVDC_CLA/HVDC_CLA.par
  examples/DynaFlow/IllustrativeExamples/HVDC_PhaseShifter/HVDC_PhaseShifter.par
  nrt/data/DynaFlow/HvdcDangling/HvdcDangling.par
  nrt/data/DynaFlow/HvdcPQPropDiagramPQ/HvdcPQPropDiagramPQ.par
  nrt/data/DynaFlow/HvdcPowerTransfer/HvdcPowerTransfer.par
  util/xsl/1898.par.xsl
Labels: Models library, DynaFlow

#2015 #2005 Remove useless copy constructors and operators
  dynawo/sources/Common/DYNParameter.cpp
  dynawo/sources/Common/DYNParameter.h
  dynawo/sources/Modeler/Common/DYNParameterModeler.cpp
  dynawo/sources/Modeler/Common/DYNParameterModeler.h
  dynawo/sources/Modeler/DataInterface/DYNStaticParameter.cpp
  dynawo/sources/Modeler/DataInterface/DYNStaticParameter.h
  dynawo/sources/Solvers/Common/DYNParameterSolver.cpp
  dynawo/sources/Solvers/Common/DYNParameterSolver.h
Labels: Code quality

#2079 #2075 Update naming conventions
  dynawo/sources/Models/Modelica/Dynawo/UsersGuide/NamingConventions.mo
Labels: Enhancement, Models library, Code quality

#2091 #2090 Fix WECC Wind OM test case
  dynawo/sources/Models/Modelica/Dynawo/Examples/Photovoltaics/WECC/PVCurrentSource.mo
Labels: Bug

#2036 #2033 Fix topological graph in case powsybl is used
  dynawo/sources/Common/DYNGraph.cpp
  dynawo/sources/Common/DYNGraph.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVoltageLevelInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestVoltageLevelInterface.cpp
  util/warnings_to_filter.txt
Labels: Bug

#2097 #1952 Add workflow_dispatch to nightly to be able to trigger job manu…
  .github/workflows/nightly.yml
Labels: DevOps

#2098 #1538 Fix Hvdc OM case
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/BlockingFunction/BlockingFunction.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/Parameters.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/HVDC/BaseModel/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Examples/HVDC/BaseModel/HvdcVSCNoBlockingFunction.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/HVDC/BaseModel/package.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/HVDC/BaseModel/package.order
  dynawo/sources/Models/Modelica/Dynawo/Examples/HVDC/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Examples/HVDC/HVDC.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/HVDC/package.order
  nrt/data/HVDC/reference/outputs/curves/curves.csv
Labels: Bug, Models library, DynaWaltz, DynaSwing

#2088 #2087 New, simple limiter
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/Limiter.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/package.order
Labels: Models library, DynaSwing

#2111 #2110 Change type of distrib used for cxx11 distrib.
  .github/workflows/release.yml
Labels: DevOps

#1938 #1930 Refactoring of timelineFilter. Adding zip treatement
  util/timeline_filter/timelineFilter.py
Labels: Enhancement, DynaWaltz

#2129 #2120 Update vsconfig to add deploy task.
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
Labels: Ease of Use
