Repository dynawo/dynawo, pull requests merged in 2022-12, with the labels that each got.

#2649 #2648 Fix nrt v1.3
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/curves/curves.csv
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/initValues/globalInit/dumpInitValues-LOADVAR_LOAD3.txt
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/initValues/globalInit/dumpInitValues-LOADVAR_LOAD3_P.txt
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/initValues/globalInit/dumpInitValues-LOADVAR_LOAD3_Q.txt
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/logs/dynawo.log
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/timeLine/timeline.log
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-LoadVariation.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-LoadVariation_P.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-LoadVariation_Q.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/initValues/globalInit/dumpInitValues-NETWORK.txt
  nrt/data/IEEE57/IEEE57_BasicTestCases/IEEE57_1_StepLoad/reference/outputs/logs/dynawo.log
Labels: Bug

#2651 #2578 Fix dynawo.cmd for local use.
  dynawo/sources/Launcher/dynawo.cmd.in
Labels: Bug

#2656 #2655 Workflow to build dynawo on Windows nightly.
  .github/workflows/nightly-release-windows.yml
Labels: Enhancement, DevOps

#2657 #2655 Fix directory not existing.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2658 #2655 Fix checkout.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2660 #2655 Debug upload for windows release.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2661 #2655 Try to fix upload of big assets.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2663 #2655 Change url for upload.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2665 #2655 Add back change of directory for uploads.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2643 #2641 fix OpenModelica compiler build on Windows
  README.md
  dynawo/3rdParty/CMakeLists.txt
Labels: Bug, 3rd party

#2671 #2655 Debug upload failing.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2672 #2655 Put back 3rd parties.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2674 #2655 Put back Dynawo build.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2681 #2655 Try to fix curl.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2645 #2619 fix multi switch
  dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.cpp
  dynawo/sources/Modeler/ModelManager/DYNModelManagerOwnFunctions.h
  dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/factory.py
  dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/readerOMC.py
  dynawo/sources/ModelicaCompiler/Scripts_OMC_1_13_2/utils.py
  dynawo/sources/ModelicaCompiler/test/ModelicaModel/reference_Test/Test_DynSilentZ.cpp
Labels: Bug

#2683 #2655 Clean debug and better handle of version number.
  .github/workflows/nightly-release-windows.yml
Labels: Bug, DevOps

#2682 #2673 Stop integrating when in limitations for VRRemote and SVC
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/SecondaryVoltageControl/Simplified/SecondaryVoltageControl.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.extvar
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/VRRemote.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQProp.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQPropDiagramPQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQPropDiagramPQSFR.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQPropDiagramPQSFR_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQPropDiagramPQ_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQPropSFR.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQPropSFR_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Machines/SignalN/GeneratorPQProp_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/PIFreeze.mo
  nrt/data/DynaFlow/VRRemote/Diagram.txt
  nrt/data/DynaFlow/VRRemote/VRRemote.crv
  nrt/data/DynaFlow/VRRemote/VRRemote.dyd
  nrt/data/DynaFlow/VRRemote/VRRemote.jobs
  nrt/data/DynaFlow/VRRemote/VRRemote.par
  nrt/data/DynaFlow/VRRemote/reference/outputs/curves/curves.csv
  nrt/data/DynaFlow/cases.py
Labels: Models library, DynaFlow

#2626 #2621 Add a dynawo test case for IEC WT4A
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/IEC/BaseConverters/ElecSystem.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/IEC/BaseConverters/GenSystem4.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/IEC/WT4Ainjector.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/MultiSwitch.mo
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource/WT4ACurrentSource.crv
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource/WT4ACurrentSource.dyd
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource/WT4ACurrentSource.jobs
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource/WT4ACurrentSource.par
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource/reference/outputs/curves/curves.csv
  nrt/data/DynaSwing/cases.py
Labels: DynaSwing, Examples
