Repository dynawo/dynawo, pull requests merged in 2023-01, with the labels that each got.

#2693 #2687 Fix slackTerminal extension to be compatible with official impl…
  dynawo/3rdParty/libiidm/patch/common/libiidm.patch
Labels: Bug, 3rd party

#2699 #2602 Fix windows xml export.
  dynawo/3rdParty/libiidm/patch/common/libiidm.patch
Labels: Bug, 3rd party

#2659 #2655 Add windows workflow in CI job.
  .github/workflows/ci.yml
Labels: Enhancement, DevOps

#2712 #2687 Fix SlackTerminal optional side attribute iidm version back to …
  dynawo/3rdParty/libiidm/patch/common/libiidm.patch
Labels: Bug, 3rd party

#2716 #2714 Fix workflow curl calls and add token.
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  .github/workflows/tools.sh
Labels: DevOps

#2701 #2700 Fix deprecated get_children
  nrt/nrt.py
Labels: Code quality

#2719 2714 fix workflow v14
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  .github/workflows/tools.sh
Labels: DevOps

#2720 2308 nightly release v1.4
  .github/workflows/nightly-release-windows.yml
  .github/workflows/nightly-release.yml
Labels: DevOps

#2727 #2725 Blank spaces and lines added or removed, points instead of comma…
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/GridFormingControlDispatchableVirtualOscillatorControl.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/GridFormingControlDroopControl.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/GridFormingControlMatchingControl.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/IEC/BaseControls/CurrentLimiter.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Steam/GovSteam1.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/PowerSystemStabilizers/Standard/PssIEEE2B.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Simplified/VRProportionalIntegral.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Simplified/VRProportionalReactiveFeedback.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/ExcIEEEST4B.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/ExcIEEEST4B_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Transformers/BaseClasses.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/TapChangerBlocking3.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/TapChangerBlocking4.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Voltage/TapChangerBlocking5.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/ElectricalControlCommon.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/DriveTrainPmConstant.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/Parameters.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Events/Event.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/BlockingFunction/GeneralBlockingFunction.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/DCVoltageControlSide.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/BaseControls/DCVoltageControlSideDangling.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSC.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSCDanglingP.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSCDanglingUdc.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/IEC/BaseConverters/RefFrameRotation.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/IEC/WT4Ainjector.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/InjectorBG.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/InjectorIDQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/InjectorURI.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/BaseControls/BlockingFunction.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/StaticVarCompensators/SVarCStandard.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Transformers/BaseClasses_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Transformers/TransformerVariableTap.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Wind/IEC/WT4ACurrentSource.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/ENTSOE/TestCase1.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/ENTSOE/TestCase2.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/ENTSOE/TestCase3.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/GridForming/GridForming.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/HVDC/HVDC.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/Grid/FullStaticModel.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Nordic/TestCases/LoadFlow.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Photovoltaics/WECC/PVCurrentSource.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Photovoltaics/WECC/PVVoltageSource.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/SMIBStepPm.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/Standard/GovSteam1ExcIEEEST4BPssIEEE2B1.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/Standard/GovSteam1ExcIEEEST4BPssIEEE2B2.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/SMIB/Standard/GovSteam1ExcIEEEST4BPssIEEE2B3.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCFaultImp.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCLoadVarQ.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCLoadVarQLarge.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCModeChange.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/SVarC/SVarCStepUref.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WTG4ACurrentSource.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WTG4BCurrentSource.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/BacklashHysteresis.mo
Labels: Code quality

#2726 #2670 fix incomplete deployment and path separator on windows
  dynawo/sources/Common/DYNFileSystemUtils.cpp
  dynawo/sources/Common/DYNIoDico.cpp
  util/windows/deploy.cmd
Labels: Code quality, DevOps

#2728 #2687 Fix slackTerminal extension to be compatible with official impl…
  dynawo/3rdParty/libiidm/patch/common/libiidm.patch
Labels: Bug, 3rd party

#2729 #2670 fix incomplete deployment and path separator on windows
  dynawo/sources/Common/DYNFileSystemUtils.cpp
  dynawo/sources/Common/DYNIoDico.cpp
  util/windows/deploy.cmd
Labels: Bug

#2736 #2714 Update api to use token in workflow and avoid github limite rate.
  .github/workflows/nightly-release-windows.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  .github/workflows/tools.sh
Labels: DevOps

#2738 #2714 Update api to use token in workflow and avoid github limit rate.
  .github/workflows/nightly-release-windows.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  .github/workflows/tools.sh
Labels: DevOps

#2746 #2745 Correct FOCB (IEC WT)
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Sources/IEC/BaseConverters/GenSystem4.mo
Labels: Models library

#2743 #2742 Create a CLA model with two threshold and two monitored currents
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Current/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Current/CurrentLimitAutomaton.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Current/CurrentLimitAutomatonTwoLevels.extvar
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Current/CurrentLimitAutomatonTwoLevels.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Current/package.order
  dynawo/sources/Models/Modelica/PreassembledModels/CMakeLists.txt
  dynawo/sources/Models/Modelica/PreassembledModels/CurrentLimitAutomatonTwoLevels.xml
  nrt/data/DynaWaltz/CLATwoLevels/CLATwoLevels.crv
  nrt/data/DynaWaltz/CLATwoLevels/CLATwoLevels.dyd
  nrt/data/DynaWaltz/CLATwoLevels/CLATwoLevels.iidm
  nrt/data/DynaWaltz/CLATwoLevels/CLATwoLevels.jobs
  nrt/data/DynaWaltz/CLATwoLevels/CLATwoLevels.par
  nrt/data/DynaWaltz/CLATwoLevels/IMonitored.txt
  nrt/data/DynaWaltz/CLATwoLevels/reference/outputs/curves/curves.csv
  nrt/data/DynaWaltz/cases.py
Labels: Models library, DynaWaltz, DynaFlow
