Repository dynawo/dynawo, pull requests merged in 2023-07, with the labels that each got.

#2976 #2975 Add OPENMODELICAHOME to work with an distribution of OpenModelica.
  dynawo/sources/Models/CMakeLists.txt
Labels: 3rd party

#2983 #2981 Add second compilation of a preassembled lib in case of a broke…
  dynawo/sources/ModelicaCompiler/DYNCompileModelicaModel.cpp
Labels: Bug, Models compilation

#2982 #2978 Add codespaces config.
  .devcontainer/devcontainer.env
  .devcontainer/devcontainer.json
  .devcontainer/postCreateCommand.sh
  .vscode/switchVscodeConfig.sh
Labels: Ease of Use

#2995 #2172 Update HVDC parameters automatically
  util/xsl/2172.par.xsl
Labels: Ease of Use

#2992 #2978 Add Codespaces build info in README. Fix postCreateCommand for …
  .devcontainer/devcontainer.env
  .devcontainer/postCreateCommand.sh
  README.md
Labels: Ease of Use

#2993 #2951 replace action with javascript
  .github/release.js
  .github/workflows/nightly-release.yml
Labels: Code quality, DevOps

#3006 #2172 Filled PLL parameters on WT Modelica examples
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSCDanglingP.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/HVDC/HvdcVSC/HvdcVSCDanglingUdc.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/HVDC/HVDC.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Photovoltaics/WECC/PVCurrentSource.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Photovoltaics/WECC/PVVoltageSource.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WT4ACurrentSource.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WT4BCurrentSource.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WTG4ACurrentSource.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/Wind/WECC/WTG4BCurrentSource.mo
Labels: Models library

#3000 #2973 Add U from UPu for InfiniteBus and Bus.
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBusInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNCalculatedBusInterfaceIIDM.cpp
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/Bus.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Buses/InfiniteBus.mo
  dynawo/sources/Models/Modelica/PreassembledModels/CMakeListsModelsTargets.txt
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm/reference/outputs/initValues/globalInit/dumpInitValues-busInf.txt
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.dyd
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/SMIB.par
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/curves.crv
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/globalInit/dumpInitValues-bus1.txt
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/globalInit/dumpInitValues-bus2.txt
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/globalInit/dumpInitValues-busInf.txt
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/localInit/dumpInitValues-bus1.txt
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/localInit/dumpInitValues-bus2.txt
  nrt/data/SMIB/SMIB_BasicTestCases/SMIB_1_StepPm_IIDM/reference/outputs/initValues/localInit/dumpInitValues-busInf.txt
Labels: Enhancement, Models library

#3014 #3013 Start nightlies after nightly-releases
  .github/workflows/nightly.yml
Labels: DevOps

#3017 #3016 enhance published release
  .github/release.js
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
Labels: DevOps
