Repository dynawo/dynawo, pull requests merged in 2024-02, with the labels that each got.

#3132 #3033 add MissingParFile error message
  dynawo/sources/Common/Dictionaries/DYNError_en_GB.dic
  dynawo/sources/Simulation/DYNSimulation.cpp
Labels: Enhancement, Ease of Use

#3144 #3135 : Add the possibility to modify grid protection parameters from…
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Wind/IEC/BaseClasses/BaseWPP.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Wind/IEC/BaseClasses/BaseWT4.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Wind/IEC/WPP/WPP4ACurrentSource.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Wind/IEC/WPP/WPP4BCurrentSource.mo
Labels: Models library, Ease of Use

#3142 #3141 expose angle_pu and v_pu for shunt compensators
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNShuntCompensatorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestShuntCompensatorInterface.cpp
Labels: Enhancement

#3143 #3136 Add hasInitialConditions_ member to DataInterface
  dynawo/sources/Modeler/DataInterface/DYNBusInterface.h
  dynawo/sources/Modeler/DataInterface/DYNComponentInterface.cpp
  dynawo/sources/Modeler/DataInterface/DYNComponentInterface.h
  dynawo/sources/Modeler/DataInterface/DYNConverterInterface.h
  dynawo/sources/Modeler/DataInterface/DYNDanglingLineInterface.h
  dynawo/sources/Modeler/DataInterface/DYNGeneratorInterface.h
  dynawo/sources/Modeler/DataInterface/DYNLccConverterInterface.h
  dynawo/sources/Modeler/DataInterface/DYNLineInterface.h
  dynawo/sources/Modeler/DataInterface/DYNLoadInterface.h
  dynawo/sources/Modeler/DataInterface/DYNShuntCompensatorInterface.h
  dynawo/sources/Modeler/DataInterface/DYNStaticVarCompensatorInterface.h
  dynawo/sources/Modeler/DataInterface/DYNTwoWTransformerInterface.h
  dynawo/sources/Modeler/DataInterface/DYNVscConverterInterface.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNBusInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNDanglingLineInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNGeneratorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLccConverterInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLineInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNLoadInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNShuntCompensatorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNStaticVarCompensatorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNTwoWTransformerInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNVscConverterInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestBusInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestDanglingLineInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestFictBusInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestFictTwoWTransformerInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestGeneratorInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestHvdcLineInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestLccConverterInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestLineInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestLoadInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestShuntCompensatorInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestStaticVarCompensatorInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestTwoWTransformerInterface.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/TestVscConverterInterface.cpp
Labels: Enhancement, Static model

#3148 #3091 New initialization models
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Governor_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/PowerSystemStabilizers/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/PowerSystemStabilizers/Pss_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/PowerSystemStabilizers/package.order
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Exciter_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/package.order
Labels: Initialization, DynaSwing
