Repository dynawo/dynawo, pull requests merged in 2024-09, with the labels that each got.

#3371 #3370 Update ci workflow for master build.
  .github/workflows/ci.yml
  .github/workflows/nightly-1.yml
  .github/workflows/nightly-2.yml
Labels: DevOps

#3380 #3361 Update for nodeJs 20.
  .github/workflows/ci.yml
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
Labels: DevOps

#3382 #3359 Fix missing option in envDynawo.
  util/envDynawo.sh
Labels: Bug

#3383 #3370 Fix master build in ci.
  .github/workflows/ci.yml
Labels: DevOps

#3388 #3387 Modify solver parameters for IEC examples
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource2020MQPRI0/WT4ACurrentSource2020.par
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource2020MQPRI0/reference/outputs/curves/curves.csv
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource2020MQPRI1/WT4ACurrentSource2020.par
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource2020MQPRI1/reference/outputs/curves/curves.csv
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource2020Q/WT4ACurrentSource2020.par
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource2020Q/reference/outputs/curves/curves.csv
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource2020U/WT4ACurrentSource2020.par
  examples/DynaSwing/IEC/Wind/Neplan/WT4ACurrentSource2020U/reference/outputs/curves/curves.csv
  examples/DynaSwing/IEC/Wind/Neplan/WT4BCurrentSource2020Q/WT4BCurrentSource2020.par
  examples/DynaSwing/IEC/Wind/Neplan/WT4BCurrentSource2020Q/reference/outputs/curves/curves.csv
  examples/DynaSwing/IEC/Wind/Neplan/WT4BCurrentSource2020U/WT4BCurrentSource2020.par
  examples/DynaSwing/IEC/Wind/Neplan/WT4BCurrentSource2020U/reference/outputs/curves/curves.csv
Labels: Performance, DynaSwing
