Repository dynawo/dynawo, pull requests merged in 2024-07, with the labels that each got.

#3295 #3294 Modify simulation configuration of GridForming test case and add reference
  dynawo/sources/Models/Modelica/Dynawo/Examples/GridForming/GridForming.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/GridForming/reference/GridForming_res.csv
Labels: Examples

#3293 #3292 Add info in nrt nok to print it in CI environment.
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  nrt/nrt.py
  util/nrt_diff/nrtUtils.py
Labels: Enhancement, DevOps

#3271 #3270 Use vectors instead of old pointers.
  dynawo/sources/Modeler/Common/DYNModelMulti.cpp
  dynawo/sources/Modeler/Common/DYNModelMulti.h
  dynawo/sources/Modeler/ModelManager/DYNModelManager.cpp
Labels: Code quality

#3169 #3168 LimiterAtCurrentValueWithLag created, base block shared with LimiterWithLag
  dynawo/sources/Modeler/DataInterface/DYNDanglingLineInterface.h
  dynawo/sources/Modeler/DataInterface/DYNHvdcLineInterface.h
  dynawo/sources/Modeler/DataInterface/DYNLineInterface.h
  dynawo/sources/Modeler/DataInterface/DYNPhaseTapChangerInterface.h
  dynawo/sources/Modeler/DataInterface/DYNRatioTapChangerInterface.h
  dynawo/sources/Modeler/DataInterface/DYNStepInterface.h
  dynawo/sources/Modeler/DataInterface/DYNTwoWTransformerInterface.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelHvdcLink.h
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Transformers/NetworkTransformer.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Transformers/NetworkTransformer_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/BaseClasses/BaseLimiterWithLag.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/BaseClasses/BaseLimiterWithLag_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/BaseClasses/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/BaseClasses/package.order
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/LimiterAtCurrentValueWithLag.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/LimiterAtCurrentValueWithLag_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/LimiterWithLag.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/LimiterWithLag_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/NonLinear/package.order
Labels: Models library

#3225 #3209 add IEEE118 test case in Open Modelica examples
  dynawo/sources/Models/Modelica/Dynawo/Examples/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/BaseClasses/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/BaseClasses/IEEE118Base.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/BaseClasses/package.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/BaseClasses/package.order
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/TestCases/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/TestCases/IEEE118NoEvent.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/TestCases/package.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/TestCases/package.order
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/package.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/package.order
  dynawo/sources/Models/Modelica/Dynawo/Examples/IEEE118/reference/IEEE118_res.csv
  dynawo/sources/Models/Modelica/Dynawo/Examples/package.order
Labels: Examples

#3289 #3288 Update status of bus at initialization.
  dynawo/sources/Modeler/DataInterface/test/TestDataInterface.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelBus.cpp
Labels: Bug, Models library

#3306 #3205 Update boost version for newer compiler.
  dynawo/3rdParty/CMakeLists.txt
Labels: Bug, DevOps

#3314 #3292 Invert cat for nrt reports in CI.
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
Labels: DevOps

#3308 #3307 Add nightly on Ubuntu 22.04.
  .github/workflows/nightly.yml
Labels: DevOps

#3318 #3317 Update actions checkout to v4.
  .github/workflows/ci.yml
  .github/workflows/nightly-release.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: DevOps

#3302 #3091 Exciter_INIT more widespread, pu base, alphabetical order
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Hydraulic/HyGov.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Simplified/VRNordic_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Simplified/VRProportionalIntegral_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Simplified/VRProportional_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/CMakeLists.txt
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/IEEET1.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/IEEET1_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/SEXS.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/SEXS_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/Scrx_INIT.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/St1a.extvar
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/package.order
  dynawo/sources/Models/Modelica/Dynawo/Examples/ENTSOE/TestCase1.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/ENTSOE/TestCase2.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/ENTSOE/TestCase3.mo
  dynawo/sources/Models/Modelica/Dynawo/Examples/RVS/Components/GeneratorWithControl/SteamIEEET1Frame.mo
  dynawo/sources/Models/Modelica/PreassembledModels/GeneratorSynchronousFourWindingsTGov1Sexs.xml
  dynawo/sources/Models/Modelica/PreassembledModels/GeneratorSynchronousFourWindingsTGov1SexsPss2A.xml
  dynawo/sources/Models/Modelica/PreassembledModels/GeneratorSynchronousThreeWindingsIeeeG1IeeeT1.xml
  dynawo/sources/Models/Modelica/PreassembledModels/GeneratorSynchronousThreeWindingsIeeeG1IeeeT1Tfo.xml
  examples/DynaSwing/ENTSOE/TestCase1/TestCase1.jobs
  examples/DynaSwing/ENTSOE/TestCase1/TestCase1.par
  examples/DynaSwing/ENTSOE/TestCase2/TestCase2.jobs
  examples/DynaSwing/ENTSOE/TestCase2/TestCase2.par
  examples/DynaSwing/ENTSOE/TestCase3/TestCase3.jobs
  examples/DynaSwing/ENTSOE/TestCase3/TestCase3.par
  nrt/data/DynaSwing/EntsoeTestCase3PlayBack/TestCase3.par
  util/updateXML/update1.7.0.0.py
Labels: Models library, Examples

#3312 #3311 Use OPENMODELICAHOME with generate-preassembled
  .gitignore
  dynawo/sources/Models/CMakeLists.txt
  util/envDynawo.sh
Labels: Bug

#3258 #3242 if structures rewritten in order to avoid IDA failure, useless …
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/Ac7c.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/VoltageRegulators/Standard/St6c.mo
  nrt/data/SMIB/IEEE/PmConstAc7bPss3b/reference/outputs/curves/curves.csv
  nrt/data/SMIB/IEEE/PmConstAc7cPss2c/SMIB.par
  nrt/data/SMIB/IEEE/PmConstAc7cPss2c/reference/outputs/curves/curves.csv
  nrt/data/SMIB/IEEE/PmConstSt6bPss3b/reference/outputs/curves/curves.csv
  nrt/data/SMIB/IEEE/PmConstSt6cPss6c/SMIB.par
  nrt/data/SMIB/IEEE/PmConstSt6cPss6c/reference/outputs/curves/curves.csv
Labels: Bug, Models library

#3305 #3275 Fix clang warnings.
  dynawo/sources/Models/CPP/Common/DYNModelCPP.h
  dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/DYNModelLoadRestorativeWithLimits.h
  dynawo/sources/Models/CPP/Controls/Shunts/ModelCentralizedShuntsSectionControl/DYNModelCentralizedShuntsSectionControl.h
  dynawo/sources/Models/CPP/Controls/Voltage/ModelVoltageMeasurementsUtilities/DYNModelVoltageMeasurementsUtilities.h
  dynawo/sources/Models/CPP/Events/ModelAreaShedding/DYNModelAreaShedding.h
  dynawo/sources/Models/CPP/Events/ModelVariationArea/DYNModelVariationArea.h
  dynawo/sources/Models/CPP/Events/ModelVoltageSetPointChange/DYNModelVoltageSetPointChange.h
  dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/DYNModelOmegaRef.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelNetwork.h
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.h
Labels: Code quality

#3299 #2190 Add missing reference for SIMOrder1Prediction nrt.
  nrt/data/SIMOrder1Prediction/reference/outputsSIMOrder0/curves/curves.csv
  nrt/data/SIMOrder1Prediction/reference/outputsSIMOrder0/logs/dynawo.log
  nrt/data/SIMOrder1Prediction/reference/outputsSIMOrder1/curves/curves.csv
  nrt/data/SIMOrder1Prediction/reference/outputsSIMOrder1/logs/dynawo.log
Labels: Solvers

#3325 #3313 Add new gcc11 distribution.
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
Labels: DevOps

#3337 #3326 Fix node20 issues with old OS.
  .github/workflows/nightly-release.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: Bug, DevOps

#3338 #3333 Fix opening of line and tfo following a bus switchoff.
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelTwoWindingsTransformer.cpp
Labels: Bug

#3344 #3313 Add python3 as environment variable for gcc11 workflow.
  .github/workflows/nightly-release.yml
Labels: Bug, DevOps

#3346 #3313 Fix bash syntax in workflow.
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
Labels: Bug, DevOps

#3350 #3349 Add small distrib master to use it in CI for child projects.
  .github/workflows/ci.yml
Labels: DevOps

#3348 #3347 Split nightly in two.
  .github/workflows/nightly-1.yml
  .github/workflows/nightly-2.yml
Labels: DevOps

#3351 #3349 Add missing environment variables.
  .github/workflows/ci.yml
Labels: Bug, DevOps
