Repository dynawo/dynawo, pull requests merged in 2024-06, with the labels that each got.

#3261 #3256 Fix doxygen.
  dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h
  dynawo/sources/Modeler/Common/DYNConnectorCalculatedVariable.h
  dynawo/sources/Modeler/Common/DYNSubModel.h
  dynawo/sources/Modeler/ModelManager/DYNModelManager.h
Labels: Documentation

#3156 #3151 Power with an option for negative input values
  .gitignore
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Simplified/GoverNordic.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Hydraulic/HYGOV1.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Machines/Governors/Standard/Hydraulic/HyGov.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Blocks/Continuous/Power.mo
Labels: Models library

#3277 #3210 Nb of arguments of logEvent corrected
  dynawo/sources/Models/Modelica/Dynawo/Resources/Include/logEvent.h
Labels: Bug, Models library, Examples

#3238 #3237 Modify HoldIq sign convention according to the norm
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/BaseControls/IqInjectionLogic.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/ElectricalControlWind.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Wind/WECC/BaseClasses/BaseWT4.mo
Labels: Models library

#3285 #3282 Update macro for test to avoid using same name as cmake built-i…
  dynawo/cmake/TestCoverage.cmake
  dynawo/cmake/UnitTest.cmake
  dynawo/sources/API/CRT/test/CMakeLists.txt
  dynawo/sources/API/CRV/test/CMakeLists.txt
  dynawo/sources/API/CSTR/test/CMakeLists.txt
  dynawo/sources/API/DYD/test/CMakeLists.txt
  dynawo/sources/API/EXTVAR/test/CMakeLists.txt
  dynawo/sources/API/FSV/test/CMakeLists.txt
  dynawo/sources/API/JOB/test/CMakeLists.txt
  dynawo/sources/API/LEQ/test/CMakeLists.txt
  dynawo/sources/API/PAR/test/CMakeLists.txt
  dynawo/sources/API/TL/test/CMakeLists.txt
  dynawo/sources/Common/test/CMakeLists.txt
  dynawo/sources/Modeler/Common/test/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/test/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/test/CMakeLists.txt
  dynawo/sources/Modeler/ModelManager/test/CMakeLists.txt
  dynawo/sources/Modeler/util/test/CMakeLists.txt
  dynawo/sources/ModelicaCompiler/test/CMakeLists.txt
  dynawo/sources/Models/CPP/Components/ModelLoadRestorativeWithLimits/test/CMakeLists.txt
  dynawo/sources/Models/CPP/Controls/Shunts/ModelCentralizedShuntsSectionControl/test/CMakeLists.txt
  dynawo/sources/Models/CPP/Controls/Voltage/ModelVoltageMeasurementsUtilities/test/CMakeLists.txt
  dynawo/sources/Models/CPP/Events/ModelAreaShedding/test/CMakeLists.txt
  dynawo/sources/Models/CPP/Events/ModelVariationArea/test/CMakeLists.txt
  dynawo/sources/Models/CPP/Events/ModelVoltageSetPointChange/test/CMakeLists.txt
  dynawo/sources/Models/CPP/ModelFrequency/ModelOmegaRef/test/CMakeLists.txt
  dynawo/sources/Models/CPP/ModelNetwork/test/CMakeLists.txt
  dynawo/sources/Models/Modelica/PreassembledModels/test/CMakeLists.txt
  dynawo/sources/Models/test/CMakeLists.txt
  dynawo/sources/Solvers/AlgebraicSolvers/test/CMakeLists.txt
  dynawo/sources/Solvers/Common/test/CMakeLists.txt
  dynawo/sources/Solvers/FixedTimeStep/SolverSIM/test/CMakeLists.txt
  dynawo/sources/Solvers/FixedTimeStep/SolverTRAP/test/CMakeLists.txt
  dynawo/sources/Solvers/VariableTimeStep/SolverIDA/test/CMakeLists.txt
  dynawo/sources/Solvers/util/test/CMakeLists.txt
  util/envDynawo.sh
Labels: Code quality

#3287 #3284 Adapt DynamicData API.
  dynawo/sources/Modeler/Common/DYNDynamicData.cpp
  dynawo/sources/Modeler/Common/DYNDynamicData.h
Labels: API

#3286 #3283 Install missing headers for dependents projects.
  dynawo/sources/Modeler/DataInterface/CMakeLists.txt
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/CMakeLists.txt
Labels: Code quality, API

#3298 #3297 Fix nrt fail on github action.
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  nrt/data/IEEE14/IEEE14_WithAutomata/IEEE14_TapChanger/reference/outputs/initValues/globalInit/dumpInitValues-_LOAD___3_EC.txt
Labels: Bug, DevOps
