Repository dynawo/dynawo, pull requests merged in 2025-06, with the labels that each got.

#3669 #3259 Fix wrong doxygen modifications.
  dynawo/sources/Modeler/Common/DYNConnectorCalculatedDiscreteVariable.h
  dynawo/sources/Modeler/Common/DYNModelMulti.h
Labels: Documentation

#3671 #3670 fix compilation errors
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelLine.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelShuntCompensator.cpp
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelSwitch.cpp
Labels: Models compilation

#3700 #3699 make FindClosestBBS return the node itself if it is a BBS
  dynawo/sources/Models/CPP/ModelNetwork/DYNModelVoltageLevel.cpp
Labels: Bug

#3689 #3512 On-the-fly instanciation of regulatingMode by SVarC if requested by a staticRef
  dynawo/sources/Common/Dictionaries/DYNLog_en_GB.dic
  dynawo/sources/Modeler/DataInterface/DYNComponentInterface.cpp
  dynawo/sources/Modeler/DataInterface/DYNComponentInterface.h
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNStaticVarCompensatorInterfaceIIDM.cpp
  dynawo/sources/Modeler/DataInterface/PowSyblIIDM/DYNStaticVarCompensatorInterfaceIIDM.h
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/LogKeys.mo
Labels: Enhancement

#3702 #3682 Replace Modelica variable limits blocks with the Dynawo block when limits can be equal to 0
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/Converters/EpriGFM/BaseControls/EpriVoltageControl.mo
  dynawo/sources/Models/Modelica/Dynawo/Electrical/Controls/WECC/REEC/BaseClasses/BaseREEC.mo
Labels: Bug, Models library, DynaSwing
