Repository dynawo/dynawo, pull requests merged in 2025-03, with the labels that each got.

#3591 #3544 Enabling IEEE14CLA simulation under OpenModelica
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/Constraint/logConstraintBeginData.mo
  dynawo/sources/Models/Modelica/Dynawo/NonElectrical/Logs/Constraint/logConstraintEndData.mo
  dynawo/sources/Models/Modelica/Dynawo/Resources/Include/logConstraint.h
Labels: Bug, Examples

#3595 #3594 Update seaprators in messages to avoid using default separators…
  dynawo/sources/Modeler/Common/DYNCompiler.cpp
  dynawo/sources/Modeler/Common/DYNDynamicData.cpp
  dynawo/sources/Modeler/Common/DYNModelMulti.cpp
  dynawo/sources/Modeler/Common/DYNSubModel.cpp
  dynawo/sources/Solvers/FixedTimeStep/DYNSolverCommonFixedTimeStep.cpp
  dynawo/sources/Solvers/FixedTimeStep/SolverSIM/test/TestBasics.cpp
  dynawo/sources/Solvers/VariableTimeStep/SolverIDA/DYNSolverIDA.cpp
Labels: Ease of Use

#3600 #3598 check if data interface is not null
  dynawo/sources/Simulation/DYNSimulation.cpp
Labels: Bug
